-- Cambia room_types.id y rooms.id de uuid a integer autoincremental
-- (empezando en 1), a pedido explícito: son datos públicos y de baja
-- cardinalidad (un puñado de tipos/habitaciones por hotel), así que la
-- opacidad de un UUID no aporta nada ahí y sí resta legibilidad.
--
-- reservations.id y profiles.id (ligado a auth.users) se quedan como
-- uuid a propósito: ahí sí importa que no sean adivinables/enumerables
-- — reservations ya tiene su propio identificador pensado para
-- mostrar (reservation_code); el id interno no debería dar pistas
-- sobre cuántas reservas existen en total.
--
-- Los datos existentes se preservan: se reindexan en orden de
-- creación (created_at), no se pierde ninguna fila. Todo en una sola
-- transacción: si algo falla a mitad de camino, se revierte entero.

begin;

-- ── room_types: nueva PK entera ──────────────────────────────────
alter table public.room_types add column new_id integer;

with ordered as (
  select id, row_number() over (order by created_at) as rn
  from public.room_types
)
update public.room_types rt set new_id = ordered.rn
from ordered where ordered.id = rt.id;

alter table public.room_types alter column new_id set not null;
alter table public.room_types alter column new_id add generated by default as identity;

do $$
declare
  v_max integer;
begin
  select coalesce(max(new_id), 0) into v_max from public.room_types;
  execute format('alter table public.room_types alter column new_id restart with %s', v_max + 1);
end $$;

-- ── rooms: nueva PK entera + nueva FK entera a room_types ────────
alter table public.rooms add column new_id integer;
alter table public.rooms add column new_room_type_id integer;

with ordered as (
  select id, row_number() over (order by created_at) as rn
  from public.rooms
)
update public.rooms r set new_id = ordered.rn
from ordered where ordered.id = r.id;

update public.rooms r set new_room_type_id = rt.new_id
from public.room_types rt where rt.id = r.room_type_id;

alter table public.rooms alter column new_id set not null;
alter table public.rooms alter column new_room_type_id set not null;
alter table public.rooms alter column new_id add generated by default as identity;

do $$
declare
  v_max integer;
begin
  select coalesce(max(new_id), 0) into v_max from public.rooms;
  execute format('alter table public.rooms alter column new_id restart with %s', v_max + 1);
end $$;

-- ── room_images: nueva FK entera a room_types ────────────────────
alter table public.room_images add column new_room_type_id integer;
update public.room_images ri set new_room_type_id = rt.new_id
from public.room_types rt where rt.id = ri.room_type_id;
alter table public.room_images alter column new_room_type_id set not null;

-- ── reservations: nueva FK entera a rooms ────────────────────────
alter table public.reservations add column new_room_id integer;
update public.reservations res set new_room_id = r.new_id
from public.rooms r where r.id = res.room_id;
alter table public.reservations alter column new_room_id set not null;

-- ── Quitar el respaldo de doble reserva antes de tocar room_id ───
alter table public.reservations drop constraint if exists reservations_no_overlap;

-- ── Quitar FKs y PKs viejas ───────────────────────────────────────
alter table public.rooms drop constraint if exists rooms_room_type_id_fkey;
alter table public.room_images drop constraint if exists room_images_room_type_id_fkey;
alter table public.reservations drop constraint if exists reservations_room_id_fkey;
alter table public.rooms drop constraint if exists rooms_pkey;
alter table public.room_types drop constraint if exists room_types_pkey;

-- ── Quitar columnas uuid viejas y renombrar las nuevas ───────────
alter table public.room_types drop column id;
alter table public.room_types rename column new_id to id;

alter table public.rooms drop column id;
alter table public.rooms rename column new_id to id;
alter table public.rooms drop column room_type_id;
alter table public.rooms rename column new_room_type_id to room_type_id;

alter table public.room_images drop column room_type_id;
alter table public.room_images rename column new_room_type_id to room_type_id;

alter table public.reservations drop column room_id;
alter table public.reservations rename column new_room_id to room_id;

-- ── Re-crear PKs y FKs con los tipos nuevos ──────────────────────
alter table public.room_types add primary key (id);
alter table public.rooms add primary key (id);

alter table public.rooms
  add constraint rooms_room_type_id_fkey
  foreign key (room_type_id) references public.room_types (id) on delete restrict;

alter table public.room_images
  add constraint room_images_room_type_id_fkey
  foreign key (room_type_id) references public.room_types (id) on delete cascade;

alter table public.reservations
  add constraint reservations_room_id_fkey
  foreign key (room_id) references public.rooms (id) on delete restrict;

-- ── Re-crear el respaldo de doble reserva ────────────────────────
alter table public.reservations
  add constraint reservations_no_overlap
  exclude using gist (
    room_id with =,
    reservation_occupancy(booking_mode, check_in_date, check_out_date, check_in_at, check_out_at) with &&
  )
  where (status in ('confirmed', 'checked_in'));

-- ── Funciones que reciben/devuelven room_type_id / room_id ───────
-- (confirm_reservation, reject_reservation, cancel_reservation,
-- checkin_reservation, checkout_reservation y no_show_reservation NO
-- se tocan: usan reservations%rowtype, que resuelve el tipo de
-- room_id en cada llamada según la tabla actual, sin necesitar
-- redefinición.)

drop function if exists public.search_available_rooms(date, date, integer);
create function public.search_available_rooms(
  p_check_in date,
  p_check_out date,
  p_guests integer
)
returns table (
  room_type_id integer,
  name text,
  slug text,
  short_description text,
  capacity integer,
  base_price numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select distinct rt.id, rt.name, rt.slug, rt.short_description, rt.capacity, rt.base_price
  from room_types rt
  join rooms r on r.room_type_id = rt.id
  where rt.active = true
    and r.status = 'available'
    and rt.capacity >= p_guests
    and p_check_out > p_check_in
    and not exists (
      select 1 from reservations res
      where res.room_id = r.id
        and res.status in ('confirmed', 'checked_in')
        and public.reservation_occupancy(res.booking_mode, res.check_in_date, res.check_out_date, res.check_in_at, res.check_out_at)
            && tstzrange(p_check_in::timestamp at time zone 'utc', p_check_out::timestamp at time zone 'utc', '[)')
    )
  order by rt.base_price asc;
$$;

grant execute on function public.search_available_rooms(date, date, integer) to anon, authenticated;

drop function if exists public.search_available_rooms_hourly(timestamptz, timestamptz, integer);
create function public.search_available_rooms_hourly(
  p_check_in timestamptz,
  p_check_out timestamptz,
  p_guests integer
)
returns table (
  room_type_id integer,
  name text,
  slug text,
  short_description text,
  capacity integer,
  hourly_price numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select distinct rt.id, rt.name, rt.slug, rt.short_description, rt.capacity, rt.hourly_price
  from room_types rt
  join rooms r on r.room_type_id = rt.id
  where rt.active = true
    and rt.allows_hourly = true
    and r.status = 'available'
    and rt.capacity >= p_guests
    and p_check_out > p_check_in
    and not exists (
      select 1 from reservations res
      where res.room_id = r.id
        and res.status in ('confirmed', 'checked_in')
        and public.reservation_occupancy(res.booking_mode, res.check_in_date, res.check_out_date, res.check_in_at, res.check_out_at)
            && tstzrange(p_check_in, p_check_out, '[)')
    )
  order by rt.hourly_price asc;
$$;

grant execute on function public.search_available_rooms_hourly(timestamptz, timestamptz, integer) to anon, authenticated;

drop function if exists public.create_reservation_atomic(uuid, text, date, date, timestamptz, timestamptz, integer, text, text, text, text, text);
create function public.create_reservation_atomic(
  p_room_type_id integer,
  p_booking_mode text,
  p_check_in date,
  p_check_out date,
  p_check_in_at timestamptz,
  p_check_out_at timestamptz,
  p_guest_count integer,
  p_guest_name text,
  p_guest_email text,
  p_guest_phone text,
  p_guest_document text,
  p_notes text
)
returns table (
  id uuid,
  reservation_code text,
  guest_name text,
  status text,
  booking_mode text,
  check_in_date date,
  check_out_date date,
  check_in_at timestamptz,
  check_out_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_capacity integer;
  v_active boolean;
  v_allows_hourly boolean;
  v_room_id integer;
  v_code text;
  v_reservation_id uuid;
  v_check_in_date date;
  v_check_out_date date;
  v_requested_range tstzrange;
begin
  if p_booking_mode not in ('nightly', 'hourly') then
    raise exception 'INVALID_BOOKING_MODE';
  end if;

  if p_guest_count is null or p_guest_count < 1 then
    raise exception 'INVALID_GUEST_COUNT';
  end if;

  select capacity, active, allows_hourly into v_capacity, v_active, v_allows_hourly
  from room_types
  where room_types.id = p_room_type_id;

  if not found or v_active is not true then
    raise exception 'ROOM_TYPE_NOT_FOUND';
  end if;

  if p_guest_count > v_capacity then
    raise exception 'CAPACITY_EXCEEDED';
  end if;

  if p_booking_mode = 'nightly' then
    if p_check_in is null or p_check_out is null or p_check_out <= p_check_in or p_check_in < current_date - 1 then
      raise exception 'INVALID_DATES';
    end if;
    v_check_in_date := p_check_in;
    v_check_out_date := p_check_out;
  else
    if not v_allows_hourly then
      raise exception 'HOURLY_NOT_ALLOWED';
    end if;
    if p_check_in_at is null or p_check_out_at is null or p_check_out_at <= p_check_in_at or p_check_in_at < now() then
      raise exception 'INVALID_DATES';
    end if;
    v_check_in_date := p_check_in_at::date;
    v_check_out_date := p_check_out_at::date + 1;
  end if;

  v_requested_range := public.reservation_occupancy(p_booking_mode, v_check_in_date, v_check_out_date, p_check_in_at, p_check_out_at);

  select r.id into v_room_id
  from rooms r
  where r.room_type_id = p_room_type_id
    and r.status = 'available'
    and not exists (
      select 1 from reservations res
      where res.room_id = r.id
        and res.status in ('confirmed', 'checked_in')
        and public.reservation_occupancy(res.booking_mode, res.check_in_date, res.check_out_date, res.check_in_at, res.check_out_at)
            && v_requested_range
    )
  order by r.room_number
  for update skip locked
  limit 1;

  if v_room_id is null then
    raise exception 'NO_AVAILABILITY';
  end if;

  v_code := public.generate_reservation_code();

  begin
    insert into reservations (
      reservation_code, room_id, booking_mode, guest_name, guest_email, guest_phone,
      guest_document, guest_count, check_in_date, check_out_date, check_in_at, check_out_at, notes, status
    ) values (
      v_code, v_room_id, p_booking_mode, p_guest_name, p_guest_email, p_guest_phone,
      p_guest_document, p_guest_count, v_check_in_date, v_check_out_date,
      case when p_booking_mode = 'hourly' then p_check_in_at end,
      case when p_booking_mode = 'hourly' then p_check_out_at end,
      p_notes, 'pending'
    )
    returning reservations.id into v_reservation_id;
  exception
    when exclusion_violation then
      raise exception 'NO_AVAILABILITY';
  end;

  return query
    select r.id, r.reservation_code, r.guest_name, r.status, r.booking_mode,
           r.check_in_date, r.check_out_date, r.check_in_at, r.check_out_at
    from reservations r
    where r.id = v_reservation_id;
end;
$$;

revoke execute on function public.create_reservation_atomic(
  integer, text, date, date, timestamptz, timestamptz, integer, text, text, text, text, text
) from public;
grant execute on function public.create_reservation_atomic(
  integer, text, date, date, timestamptz, timestamptz, integer, text, text, text, text, text
) to service_role;

commit;
