-- Catálogo de servicios/amenidades, asignables al hotel en general o a
-- tipos de habitación específicos. El ícono se calcula por palabras
-- clave del nombre desde el cliente (ver src/utils/serviceIcons.js) y
-- se guarda como columna real para poder editarlo desde una UI futura.

create table public.services (
  id integer generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('hotel', 'room')),
  icon text not null default 'sparkles',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.services enable row level security;

create policy "services_select_public"
  on public.services for select
  to anon, authenticated
  using (active = true);

create policy "services_select_staff"
  on public.services for select
  to authenticated
  using (public.is_staff_or_admin(auth.uid()));

create policy "services_write_staff"
  on public.services for all
  to authenticated
  using (public.is_staff_or_admin(auth.uid()))
  with check (public.is_staff_or_admin(auth.uid()));

drop trigger if exists set_updated_at on public.services;
create trigger set_updated_at
  before update on public.services
  for each row execute function public.set_updated_at();

-- Tabla puente: qué servicios (tipo "room") están asignados a qué tipo
-- de habitación. Los de tipo "hotel" se muestran automáticamente en
-- todas las habitaciones sin pasar por esta tabla.
create table public.room_type_services (
  room_type_id integer not null references public.room_types (id) on delete cascade,
  service_id integer not null references public.services (id) on delete cascade,
  primary key (room_type_id, service_id)
);

alter table public.room_type_services enable row level security;

create policy "room_type_services_select_public"
  on public.room_type_services for select
  to anon, authenticated
  using (true);

create policy "room_type_services_write_staff"
  on public.room_type_services for all
  to authenticated
  using (public.is_staff_or_admin(auth.uid()))
  with check (public.is_staff_or_admin(auth.uid()));

-- Datos iniciales: los 6 servicios que antes vivían hardcodeados en
-- siteConfig.services, para que la home y las habitaciones no queden
-- vacías tras esta migración.
insert into public.services (name, type, icon) values
  ('WiFi gratis', 'hotel', 'wifi'),
  ('Estacionamiento', 'hotel', 'car'),
  ('Agua caliente', 'hotel', 'droplet'),
  ('TV por cable', 'hotel', 'tv'),
  ('Desayuno incluido', 'hotel', 'coffee'),
  ('Recepción 24 horas', 'hotel', 'concierge-bell');
